<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>4a90b9df-bc8f-4fc6-a372-26b7a50d4695</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Handwerker.Application\Handwerker.Application.csproj" />
        <ProjectReference Include="..\Handwerker.Domain\Handwerker.Domain.csproj" />
        <ProjectReference Include="..\Handwerker.Infrastructure\Handwerker.Infrastructure.csproj" />
        <ProjectReference Include="..\Handwerker.ServiceDefaults\Handwerker.ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.6-preview.1.26319.6" />
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
        <PackageReference Include="Bogus" Version="35.6.5" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.8.0" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
        <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\uploads\companies\" />
    </ItemGroup>

</Project>
